# Generated by Django 4.1.3 on 2023-01-05 09:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('sigla_uf', models.CharField(max_length=2, verbose_name='abreviação')),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='área (km2)')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='nome')),
                ('sigla_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('cod_ibge_m', models.CharField(max_length=20, verbose_name='código IBGE')),
                ('sede_lng', models.FloatField(blank=True, null=True, verbose_name='Longitude da Sede')),
                ('sede_lat', models.FloatField(blank=True, null=True, verbose_name='Latitude da Sede')),
                ('slug', models.SlugField()),
                ('visivel', models.BooleanField(verbose_name='visível?')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapas.estado', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'ordering': ('sigla_uf', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='UtmFuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuso', models.IntegerField(verbose_name='fuso')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código EPSG')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geom')),
            ],
            options={
                'verbose_name': 'Fuso',
                'verbose_name_plural': 'Fusos',
            },
        ),
        migrations.CreateModel(
            name='MunicipioGeometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retificado', models.BooleanField(default=False, verbose_name='Retificado')),
                ('cod_ibge_m', models.CharField(max_length=20, verbose_name='código IBGE')),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área (km2)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geom')),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mapas.municipio', verbose_name='municipio')),
            ],
            options={
                'verbose_name': 'Geometria do Município',
                'verbose_name_plural': 'Geometrias dos Municípios',
                'ordering': ('cod_ibge_m',),
            },
        ),
        migrations.CreateModel(
            name='EstadoGeometria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ibge_m', models.CharField(max_length=20, verbose_name='código IBGE')),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='área (km2)')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='geom')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapas.estado', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Geometria do Estado',
                'verbose_name_plural': 'Geometrias dos Estados',
                'ordering': ['cod_ibge_m'],
            },
        ),
    ]
