# Generated by Django 4.1.3 on 2023-01-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_areaindigena_areaprotegida_assentamento_bioma_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='anunciado',
            field=models.BooleanField(default=False, verbose_name='anunciado?'),
        ),
    ]
