# Generated by Django 4.1.3 on 2023-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_car_anunciado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='anunciado',
            field=models.BooleanField(default=False, null=True, verbose_name='anunciado?'),
        ),
    ]
