# Generated by Django 4.1.3 on 2023-01-20 16:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_alter_car_anunciado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Irradiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=6, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('annual', models.IntegerField(blank=True, null=True)),
                ('jan', models.IntegerField(blank=True, null=True)),
                ('feb', models.IntegerField(blank=True, null=True)),
                ('mar', models.IntegerField(blank=True, null=True)),
                ('apr', models.IntegerField(blank=True, null=True)),
                ('may', models.IntegerField(blank=True, null=True)),
                ('jun', models.IntegerField(blank=True, null=True)),
                ('jul', models.IntegerField(blank=True, null=True)),
                ('aug', models.IntegerField(blank=True, null=True)),
                ('sep', models.IntegerField(blank=True, null=True)),
                ('oct', models.IntegerField(blank=True, null=True)),
                ('nov', models.IntegerField(blank=True, null=True)),
                ('dec', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='LinhaTransmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=70, null=True)),
                ('tensao_kv', models.BigIntegerField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=16, null=True)),
                ('tipo_rede', models.CharField(blank=True, max_length=18, null=True)),
                ('agente', models.CharField(blank=True, max_length=19, null=True)),
                ('km', models.FloatField(blank=True, null=True)),
                ('dt_ent_op', models.CharField(blank=True, max_length=11, null=True)),
                ('dt_prev_op', models.CharField(blank=True, max_length=13, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Subestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=35, null=True)),
                ('situacao', models.CharField(blank=True, max_length=14, null=True)),
                ('municipio', models.CharField(blank=True, max_length=35, null=True)),
                ('uf', models.CharField(blank=True, max_length=4, null=True)),
                ('munic_uf', models.CharField(blank=True, max_length=40, null=True)),
                ('geocodigo', models.BigIntegerField(blank=True, null=True)),
                ('mw', models.FloatField(blank=True, null=True)),
                ('empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('nome3', models.CharField(blank=True, max_length=250, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
