# Generated by Django 4.1.3 on 2023-01-27 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0005_irradiacao_linhatransmissao_subestacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapAguaDisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.CharField(max_length=80)),
                ('subordem', models.CharField(max_length=80)),
                ('grande_gru', models.CharField(max_length=80)),
                ('subgrupos', models.CharField(max_length=80)),
                ('textura', models.CharField(max_length=80)),
                ('awc', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
