# Generated by Django 4.1.3 on 2023-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0006_capaguadisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capaguadisp',
            name='grande_gru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capaguadisp',
            name='ordem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capaguadisp',
            name='subgrupos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capaguadisp',
            name='subordem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='capaguadisp',
            name='textura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
