# Generated by Django 4.1.3 on 2023-01-27 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0007_alter_capaguadisp_grande_gru_alter_capaguadisp_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capaguadisp',
            name='awc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capaguadisp',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
