# Generated by Django 4.1.3 on 2023-02-04 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0008_alter_capaguadisp_awc_alter_capaguadisp_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadogeometria',
            name='estado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mapas.estado', verbose_name='estado'),
        ),
    ]
