# Generated by Django 4.1.3 on 2023-01-18 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapas', '0002_areaindigena_areaprotegida_assentamento_bioma_car_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Propriedade')),
                ('matricula', models.CharField(max_length=50, verbose_name='Número da Matrícula do Imóvel')),
                ('nome_responsavel', models.CharField(max_length=50, verbose_name='Nome do Responsável')),
                ('email_responsavel', models.EmailField(max_length=254, verbose_name='E-mail do Responsável')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('informacoes_divulgaveis', models.CharField(choices=[('telefone-email', 'Telefone e E-mail'), ('telefone', 'Apenas Telefone'), ('email', 'Apenas E-mail')], max_length=20, verbose_name='Informações Divulgavéis')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Propriedade')),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área da Propriedade (ha)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Comercialização')),
                ('divulga_preco', models.BooleanField(default=False, verbose_name='Divulgar Preço do Imóvel')),
                ('tipo_transacao', models.CharField(choices=[('venda', 'Venda'), ('troca', 'Troca'), ('arrendamentao', 'Arrendamentao')], max_length=20, verbose_name='Tipo Transação')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estrutura',
                'verbose_name_plural': 'Estruturas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('arquivo', models.FileField(upload_to='anuncios/arquivos', verbose_name='Arquivo')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='anuncios.anuncio', verbose_name='Anúncio')),
            ],
            options={
                'verbose_name': 'Arquivo do Anúncio',
                'verbose_name_plural': 'Arquivos dos Anúncios',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='estruturas',
            field=models.ManyToManyField(blank=True, to='anuncios.estrutura', verbose_name='Estruturas na Propriedade'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapas.municipio', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
    ]
