# Generated by Django 4.1.3 on 2023-02-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcaoDiversos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('categoria', models.CharField(max_length=30, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Opção para Anúncio Diversos',
                'verbose_name_plural': 'Opções para Anúncios Diversos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Tipo do Serviço',
                'verbose_name_plural': 'Tipos de Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_anuncio',
            field=models.CharField(choices=[('propriedade', 'Propriedade'), ('reserva-legal', 'Reserva Legal'), ('energia-solar', 'Energia Solar'), ('equipamentos', 'Equipamentos'), ('servicos', 'Serviços'), ('diversos', 'Diversos')], default='propriedade', max_length=20, verbose_name='Tipo do Anúncio'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_bioma',
            field=models.CharField(blank=True, choices=[('Amazônia', 'Amazônia'), ('Caatinga', 'Caatinga'), ('Cerrado', 'Cerrado'), ('Mata Atlântica', 'Mata Atlântica'), ('Pampa', 'Pampa'), ('Pantanal', 'Pantanal')], max_length=20, verbose_name='Tipo do Bioma'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_propriedade',
            field=models.CharField(blank=True, choices=[('Fazenda', 'Fazenda'), ('Chácara', 'Chácara'), ('Sítio', 'Sítio'), ('Rancho', 'Rancho'), ('Outros', 'Outros')], max_length=30, verbose_name='Tipo da Propriedade'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('Hectare', 'Hectare'), ('Alqueire', 'Alqueire'), ('Alqueire Mineiro/Alqueire Geométrico', 'Alqueire Mineiro/Alqueire Geométrico'), ('Alqueire Paulista', 'Alqueire Paulista'), ('Braça Quadrada', 'Braça Quadrada'), ('Data', 'Data'), ('Légua Quadrada', 'Légua Quadrada'), ('Litro', 'Litro'), ('Metro Quadrado', 'Metro Quadrado'), ('Mil Covas', 'Mil Covas'), ('Quarta', 'Quarta'), ('Tarefa', 'Tarefa'), ('Tarefa Baiana', 'Tarefa Baiana')], max_length=40, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='area_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área da Propriedade (ha)'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número da Matrícula do Imóvel'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Comercialização'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_transacao',
            field=models.CharField(choices=[('venda', 'Venda'), ('troca', 'Troca'), ('arrendamento', 'Arrendamento')], max_length=20, verbose_name='Tipo Transação'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='opcao_diversos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.opcaodiversos', verbose_name='Opção'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.tiposervico', verbose_name='Tipo do Serviço'),
        ),
    ]
