# Generated by Django 4.1.3 on 2023-02-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_opcaodiversos_tiposervico_anuncio_tipo_anuncio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='opcao_diversos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anuncios.opcaodiversos', verbose_name='Opção Diversos'),
        ),
    ]
