# Generated by Django 4.1.3 on 2023-02-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncio_destaque_alter_anuncio_opcao_diversos'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios/fotos', verbose_name='Foto'),
        ),
    ]
