# Generated by Django 4.1.3 on 2023-02-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_alter_artigo_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tipo_artigo',
            field=models.CharField(choices=[('artigos', 'artigos'), ('noticias', 'noticias'), ('cursos', 'cursos'), ('clica', 'clica')], max_length=20, verbose_name='Tipo do Artigo'),
        ),
    ]
