# Generated by Django 4.1.3 on 2023-02-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_alter_artigo_texto_alter_artigo_tipo_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='tipo_artigo',
            field=models.CharField(choices=[('artigos', 'artigos'), ('noticias', 'noticias'), ('cursos', 'cursos'), ('clima', 'clima')], max_length=20, verbose_name='Tipo do Artigo'),
        ),
    ]
