# Generated by Django 4.1.3 on 2023-01-05 09:51

from django.db import migrations, models
import django.db.models.deletion
import geofazendas.seguranca.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mapas', '0001_initial'),
        ('sindicatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('telefone', models.CharField(max_length=20, verbose_name='Celular')),
                ('codigo', models.CharField(max_length=6, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Envio SMS',
                'verbose_name_plural': 'Envios SMS',
                'ordering': ['-criado'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ativo', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('identificador', models.CharField(max_length=50, unique=True, verbose_name='Identificador')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=11, verbose_name='Telefone')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('ultimo_acesso', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapas.municipio', verbose_name='Município')),
                ('sindicato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sindicatos.sindicato', verbose_name='Sindicato')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-nome'],
            },
            managers=[
                ('objects', geofazendas.seguranca.models.UsuarioManager()),
            ],
        ),
    ]
